### PR TITLE
Small edits in Entities package

### PR DESCRIPTION
**Pull request by ZiadMohamed9**
I made class Department record and improved the usage of command in Employee and Supervisor classes by adding an attribute command:IAttendanceCommand and a setter to change the command in every method.

### CODE REVIEW

**Comment by mistaluai** [comment]
Looks fine to me.

**Comment by BlindFl0W** [comment]
Can you explain the purpose of the changes in the department class.

**Comment by ZiadMohamed9** [comment]
No purpose, record is just a keyword in java used in such situations makes the code easier and cleaner.

**Comment by BlindFl0W** [comment]
You have deleted the whole department class and replaced it with only this 
```public record Department(String departmentName, String supervisor) {}```

**Comment by mistaluai** [comment]
> You have deleted the whole department class and replaced it with only this `public record Department(String departmentName, String supervisor) {}`

this is used basically when the class it just holding data with no actual logic or implementations, which is a pretty smart move by Ziad.

**Review by mistaluai — APPROVED** [review]

**Pull request merged**
